services:
  web:
    image: nginx:stable-alpine3.21-perl
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/public
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - quiz_network

  app:
    build: .
    container_name: fastapi_app
    volumes:
      - ./src:/app/src
    env_file:
      - ./.docker/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - quiz_network

  migration:
    profiles: ["migration"]
    build: .
    container_name: alembic_migration
    command: alembic upgrade head
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.docker/.env
    networks:
      - quiz_network

  database:
    image: postgres:16.10-alpine3.22
    shm_size: 128mb
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=user
    env_file:
      - ./.docker/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d quiz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/init_scripts:/docker-entrypoint-initdb.d
    networks:
      - quiz_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - quiz_network

  redis:
    image: redis:8.4-rc1-alpine3.22
    container_name: redis_session_cache
    ports:
      - 6379:6379


volumes:
  postgres_data:

networks:
  quiz_network:
    driver: bridge
